version: '3.8'

services:
  react_app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"  # Проброс порта 3000 на локальной машине на порт 80 контейнера
    volumes:
      - .:/app