version: '3'
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  fastapi_webapp:
    ports:
      - "443:8000"
    build:
      context: .
      dockerfile: backend/api/Dockerfile
    volumes:
      - .:/app

    environment:
      - PYTHONUNBUFFERED=1
