version: '3'
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    # Можно указать другой порт для доступа к приложению
    # ports:
    #   - "8080:80"
    # volumes:g
    #   - ./frontend/nginx.conf:/etc/nginx/nginx.conf

